---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-system
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-default
  labels:
    istio-injection: enabled
    cf: enabled
    org_id: cf-default
    org_name: cf-default
    space_id: cf-default
    space_name: cf-default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cf-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io